### ISSUE TITLE
Second level domain support

### ISSUE THREAD

**Issue by bjarneo** [bjarneo/extract-domain#1]
https://en.wikipedia.org/wiki/Second-level_domain

*.co.uk

**Comment by jamesjara** [comment]
+1

**Comment by bjarneo** [comment]
I'm still trying to figure ut a pattern to solve this though. Since I don't use regex.

**Comment by Kikobeats** [comment]
exists a regex for do that?

**Comment by bjarneo** [comment]
~~Yeah, it exists. This code was initially trying to extract the hostname/domain without the use of regex, but I am considering switching to regex since this code is not that performant any more.~~

**Comment by Kikobeats** [comment]
related: https://stackoverflow.com/questions/21173734/extracting-top-level-and-second-level-domain-from-a-url-using-regex

**Comment by Kikobeats** [comment]
Inspiration: https://github.com/peerigon/parse-domain

**Comment by Kikobeats** [comment]
https://github.com/peerigon/parse-domain/blob/master/lib/tld.js

**Comment by bjarneo** [comment]
Thanks for links. This issue has been open for a year now. I think I'll revisit the logic today (and this week). Try to get a new release with second level domain support :)

**Comment by Kikobeats** [comment]
let me if you need help 🙂

**Comment by bjarneo** [comment]
I'm so slow at github at the moment. :|

But, I'm looking into actually create this domain extraction the same as creating a programming language. Create a parser, tokenizer and ast. Not sure how performant that will be, but just for the fun of it. Then it will probably be much easier to extract the second level domain. 

However, I guess an approach where we just use regex would be faster though.

**Comment by bjarneo** [comment]
Have been investigating SLDs, regex, and such. This is a tricky thing to do.

Seems that I actually need a list of SLDs to do this. 

Will continue investigating.

**Comment by bjarneo** [comment]
Nice place to test regex. This is just a simple test by checking for dots and words: https://regex101.com/r/2Gd219/1

**Comment by bjarneo** [comment]
One easy approach would be returning `subdomain.domain.co.uk`, but then again, it will not behave as I expect this library to behave.

**Comment by ddemid** [comment]
+1

**Comment by bjarneo** [comment]
Two years later, a "hack" for second level domain support is added. All tests are passing.

**Comment by bjarneo** [comment]
Nope. Forgot about sub domains. This "hack" didn't work. Reverting.

**Comment by danipolo** [comment]
+1 !!!

**Comment by misner** [comment]
+1

**Comment by LeCoupa** [comment]
You can check how this package is doing it to validate second-level domains.

https://github.com/miguelmota/is-valid-domain

**Comment by bjarneo** [comment]
Here is the PR with details: https://github.com/bjarneo/extract-domain/pull/7
