### ISSUE TITLE
extractDomain("https://www.google.co.uk") = "co.uk"

### ISSUE THREAD

**Issue by dancherb** [bjarneo/extract-domain#10]
Thanks for the work - currently this can't be used with multi-part domain endings such as .co.uk or .com.au (and countless others).

**Comment by bjarneo** [comment]
Hey. Did you try with extractDomain('https://www.google.co.uk', { tld: true })?

**Comment by bjarneo** [comment]
```
➜  extract-domain-test cat index.js
const extractDomain = require("extract-domain");

console.log(extractDomain("https://www.google.co.uk", { tld: true }))
➜  extract-domain-test node index.js
google.co.uk
```
https://github.com/bjarneo/extract-domain#tld-support

**Comment by dancherb** [comment]
> Hey. Did you try with extractDomain('https://www.google.co.uk', { tld: true })?

Oops. Cheers boss
