### ISSUE TITLE
Problem with returning domains with no subdomain

### ISSUE THREAD

**Issue by lf-gcote** [bjarneo/extract-domain#12]
I'm currently using this library to extract the domain of a website and I'm running into issues.

https://www.test.com returns **test.com**
https://test.com returns **null**

Expected result:
https://test.com returns **test.com**

EDIT: The TLD option is set to TRUE
EDIT2: When the TLD option is set to FALSE, everything works accordingly

**Comment by bjarneo** [comment]
Ahh, great catch. Will look into this. Thank you!

**Comment by bjarneo** [comment]
Should be fixed in version extract-domain@2.3.4

**Comment by bjarneo** [comment]
https://github.com/bjarneo/extract-domain/commit/2dc222c73d19d2dd4f7225faddd85a1e3c323658
