### ISSUE TITLE
unable to extract domain when the non-domain part is less than 5 chars

### ISSUE THREAD

**Issue by thenextbiglogicprovider** [bjarneo/extract-domain#2]
I tried to extract the domain from this username 'test@something.com' and got a blank string but when i tried with 'test1@something.com' i got the domain part 'something.com'.

please make this one work for less than 5 chars too.

**Comment by bjarneo** [comment]
Oh, that's not good. I'll look into this asap :) Thanks for reaching out!

**Comment by bjarneo** [comment]
@thenextbiglogicprovider it has been fixed. Version 2.0.6.
