### ISSUE TITLE
Getting extractDomain.default is not a function

### ISSUE THREAD

**Issue by geraldosalazar16** [bjarneo/extract-domain#31]
I tried to import as per the library docs 
` import extractDomain from 'extract-domain';`
 And then use it like 
```
const urls = await extractDomain("https://www.mydomain", {
 tld: true,
 });
```

 but it throws
 **extractDomain.default is not a function**

 Also tried 
` import * as extractDomain from 'extract-domain';`
 And then use it like 
```
const urls = await extractDomain.default("https://www.mydomain", {
 tld: true,
 });
```
 
 But got the same error

The only way I was able to make it work was by doing 
`const extractDomain = require('extract-domain');`
And then use like in the first case

I am using typescript 5.1.6

**Comment by geraldosalazar16** [comment]
I created this [repo](https://github.com/geraldosalazar16/test-extract-domain) reproduce and this [stackblitz](https://stackblitz.com/edit/nestjs-typescript-starter-l5p69g?file=README.md) to reproduce

**Comment by bjarneo** [comment]
Thanks. This is strange behaviour. I will look into this!

**Comment by bjarneo** [comment]
From version 5, it will support ESM only.
