### ISSUE TITLE
Does not work for third level domains

### ISSUE THREAD

**Issue by ojurkiewicz** [bjarneo/extract-domain#6]
Example:
```extractDomain('https://www.argos.co.uk/');```

Expected result: 
```argos.co.uk```
Current result:
```co.uk```

Possible solution:
Check against some good TLD list. For example: https://publicsuffix.org/list/public_suffix_list.dat

**Comment by bjarneo** [comment]
Hi. Thanks for the issue. One does already exist, can be found at #1.

I've though about what you mentioned, but that will increase the size for this library drastically. However, one thought is to create a separate lib to support both.

**Comment by ojurkiewicz** [comment]
So sorry, should've read that before posting. It will increase the size (but i would argue if drastically 😉) but as far as i'm concerned this is the only way to get 100% accurate results.

**Comment by bjarneo** [comment]
No need for sorry :) 

Regarding the size, this file is 215K large 😄: https://publicsuffix.org/list/public_suffix_list.dat

Could of course do some magic to fetch only when needed

**Comment by sadortun** [comment]
@bjarneo You could also strip the file down as part of the build process and reduce it to a nested array. where the top level indices match TLD names ex: `{"ac": { 'com', ' 'edu','gov' }}`

**Comment by madeindjs** [comment]
I think you could use [psl librairy](https://www.npmjs.com/package/psl). The minified size is "only" 127kb.

**Comment by bjarneo** [comment]
@madeindjs I caved in and used the psl lib. Here are the details: https://github.com/bjarneo/extract-domain/pull/7
